In [16]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import stat
import shutil
from tqdm import tqdm
from sklearn.manifold import TSNE
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("trainLabels.csv")
df.head()

                     Id  Class
0  01kcPWA9K2BOxQeS5Rju      1
1  04EjIdbPV5e1XroFOpiN      1
2  05EeG39MTRrI6VY21DPd      1
3  05rJTUWYAKNegBk2wE8X      1
4  0AnoOZDNbPXIr2MRBSCJ      1

In [3]:
data = []

l = ["00","01","02","03","04","05","06","07","08","09","0A","0B","0C","0D","0E","0F","10","11","12","13","14","15","16","17","18","19","1A","1B","1C","1D","1E","1F","20","21","22","23","24","25","26","27","28","29","2A","2B","2C","2D","2E","2F","30","31","32","33","34","35","36","37","38","39","3A","3B","3C","3D","3E","3F","40","41","42","43","44","45","46","47","48","49","4A","4B","4C","4D","4E","4F","50","51","52","53","54","55","56","57","58","59","5A","5B","5C","5D","5E","5F","60","61","62","63","64","65","66","67","68","69","6A","6B","6C","6D","6E","6F","70","71","72","73","74","75","76","77","78","79","7A","7B","7C","7D","7E","7F","80","81","82","83","84","85","86","87","88","89","8A","8B","8C","8D","8E","8F","90","91","92","93","94","95","96","97","98","99","9A","9B","9C","9D","9E","9F","A0","A1","A2","A3","A4","A5","A6","A7","A8","A9","AA","AB","AC","AD","AE","AF","B0","B1","B2","B3","B4","B5","B6","B7","B8","B9","BA","BB","BC","BD","BE","BF","C0","C1","C2","C3","C4","C5","C6","C7","C8","C9","CA","CB","CC","CD","CE","CF","D0","D1","D2","D3","D4","D5","D6","D7","D8","D9","DA","DB","DC","DD","DE","DF","E0","E1","E2","E3","E4","E5","E6","E7","E8","E9","EA","EB","EC","ED","EE","EF","F0","F1","F2","F3","F4","F5","F6","F7","F8","F9","FA","FB","FC","FD","FE","FF"]

for i in tqdm(df["Id"].values):
    with open("F://microsoft malware detection//text//" + i + ".text", "r") as fp:
        x = fp.read().split()
        count = [x.count(j) for j in l]
        data.append(count)

100%|█████████████████████████████████████████████████████████████████████████| 10868/10868 [23:27:17<00:00,  3.26s/it]

In [4]:
len(data)

10868

In [5]:
len(data[0])

256

In [6]:
df_bow = pd.DataFrame(data)

In [7]:
df_bow.to_csv("bow.csv", index = False)

In [8]:
df_bow.columns = ["00","01","02","03","04","05","06","07","08","09","0A","0B","0C","0D","0E","0F","10","11","12","13","14","15","16","17","18","19","1A","1B","1C","1D","1E","1F","20","21","22","23","24","25","26","27","28","29","2A","2B","2C","2D","2E","2F","30","31","32","33","34","35","36","37","38","39","3A","3B","3C","3D","3E","3F","40","41","42","43","44","45","46","47","48","49","4A","4B","4C","4D","4E","4F","50","51","52","53","54","55","56","57","58","59","5A","5B","5C","5D","5E","5F","60","61","62","63","64","65","66","67","68","69","6A","6B","6C","6D","6E","6F","70","71","72","73","74","75","76","77","78","79","7A","7B","7C","7D","7E","7F","80","81","82","83","84","85","86","87","88","89","8A","8B","8C","8D","8E","8F","90","91","92","93","94","95","96","97","98","99","9A","9B","9C","9D","9E","9F","A0","A1","A2","A3","A4","A5","A6","A7","A8","A9","AA","AB","AC","AD","AE","AF","B0","B1","B2","B3","B4","B5","B6","B7","B8","B9","BA","BB","BC","BD","BE","BF","C0","C1","C2","C3","C4","C5","C6","C7","C8","C9","CA","CB","CC","CD","CE","CF","D0","D1","D2","D3","D4","D5","D6","D7","D8","D9","DA","DB","DC","DD","DE","DF","E0","E1","E2","E3","E4","E5","E6","E7","E8","E9","EA","EB","EC","ED","EE","EF","F0","F1","F2","F3","F4","F5","F6","F7","F8","F9","FA","FB","FC","FD","FE","FF"]

In [9]:
sizes = []

for i in df["Id"].values:
    size = os.path.getsize('F://microsoft malware detection//bytes//' + i + '.bytes')/(1024)
    sizes.append(size)
    
df["size"] = sizes

In [10]:
result = pd.concat([df, df_bow], axis=1)
result.shape

(10868, 259)

In [11]:
result.head()

,Id,Class,size,00,01,02,03,04,05,06,...,F6,F7,F8,F9,FA,FB,FC,FD,FE,FF
0,01kcPWA9K2BOxQeS5Rju,1,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,04EjIdbPV5e1XroFOpiN,1,870.0,40030,1980,1226,1193,1971,1096,961,...,585,377,806,479,357,394,1114,507,1080,10826
2,05EeG39MTRrI6VY21DPd,1,522.0,19419,955,693,656,832,463,370,...,348,434,463,354,472,393,384,303,390,2104
3,05rJTUWYAKNegBk2wE8X,1,2856.5,79568,6445,3143,2517,4982,1824,2125,...,2626,3753,4012,1511,1604,2407,5196,4614,4448,47484
4,0AnoOZDNbPXIr2MRBSCJ,1,580.0,25791,1202,569,750,948,456,405,...,385,402,500,316,297,343,452,283,401,4532